### ISSUE TITLE
Need Some Help!!!

### ISSUE THREAD

**Issue by YaseenYo** [sparecycles/sparecycles.github.src#1]
Hello @sparecycles, its Mohammed here. I am completely new to open source, so I tried looking some projects to contribute, And I found TypeScript. I am not getting where to start with. So pls can you help me get started, It would be really helpful...

**Comment by sparecycles** [comment]
Well, the source for my personal github pages site is not the right place.  Nor is it appropriate for you to ask such a broad question to a single person.  I'm sorry but the profession of teacher exists for a reason.

I would look into finding forums, maybe, where a broader set of people/experience levels may help bridge the gap between where you are (which I have no real idea of so I can't begin to offer any advice) and where you want to be (also unspecified but I doubt you can even imagine what that is at this point).

**Comment by YaseenYo** [comment]
Thanks a lot!!!
